repos:
    -   repo: https://github.com/psf/black
        rev: 22.3.0
        hooks:
        -   id: black
            exclude: >
              (?x)^(
                swig/python/osgeo/|
                autotest/ogr/data/
              )
    -   repo: https://github.com/timothycrosley/isort
        rev: 5.12.0
        hooks:
        -   id: isort
            exclude: >
              (?x)^(
                swig/python/osgeo/|
                autotest/ogr/data/
              )
    -   repo: https://github.com/pycqa/flake8
        rev: 3.9.2
        hooks:
        -   id: flake8
            exclude: >
              (?x)^(
                swig/python/osgeo/|
                examples/|
                autotest/ogr/data/
              )
    -   repo: https://github.com/pre-commit/mirrors-clang-format
        rev: 'v15.0.7'
        hooks:
        -   id: clang-format
            exclude: >
              (?x)^(
                autotest/cpp/data/|
                autotest/gdrivers/data/|
                swig/|
                third_party/|
                autotest/ogr/data/|
                alg/internal_libqhull/|
                apps/argparse/|
                frmts/gtiff/libtiff/|
                frmts/gtiff/libgeotiff/|
                frmts/hdf4/hdf-eos/|
                frmts/jpeg/libjpeg/|
                frmts/jpeg/libjpeg12/|
                frmts/pcraster/libcsf/|
                frmts/png/libpng/|
                frmts/gif/giflib/|
                frmts/zlib/|
                frmts/pcidsk/sdk|
                frmts/grib/degrib/degrib|
                frmts/grib/degrib/g2clib|
                port/utf8.h|
                ogr/ogrsf_frmts/cad/libopencad/|
                ogr/ogrsf_frmts/geojson/libjson/|
                ogr/ogrsf_frmts/flatgeobuf/flatbuffers/|
                ogr/ogrsf_frmts/pmtiles/pmtiles/|
                ogr/ogrsf_frmts/sqlite/sqlite_rtree_bulk_load
              )
