# This is the config file for building GDAL and running its autotest suite
# with Travis-ci.org

branches:
  except:
  - /^(cherry-pick-)?backport-\d+-to-/

matrix:
  fast_finish: true
  include:

#    - os: linux
#      compiler: gcc
#      language: cpp
#      sudo: required
#      dist: bionic
#      cache:
#        apt: true
#        directories:
#          - $HOME/.ccache
#      env:
#        - BUILD_NAME=ubuntu_1804
#        - DETAILS=""

#    - os: linux
#      compiler: clang
#      language: cpp
#      sudo: required
#      dist: trusty
#      cache:
#        apt: true
#        directories:
#          - $HOME/.ccache
#      env:
#        - BUILD_NAME=trusty_clang
#        - DETAILS="optimized build, no libtool"

#    - os: linux
#      compiler: clang
#      language: cpp
#      sudo: required
#      dist: trusty
#      cache:
#        apt: true
#        directories:
#          - $HOME/.ccache
#      env:
#        - BUILD_NAME=mingw_w64
#        - DETAILS="optimized build, libtool"

#    - os: linux
#      compiler: gcc
#      language: cpp
#      sudo: required
#      dist: xenial
#      cache:
#        apt: true
#        directories:
#          - $HOME/.ccache
#      env:
#        - BUILD_NAME=python3
#        - DETAILS=""

#    - os: linux
#      compiler: gcc
#      language: cpp
#      sudo: false
#      dist: trusty
#      cache:
#        apt: true
#        directories:
#          - $HOME/.ccache
#      apt:
#        packages:
#          - ccache
#      env:
#        - BUILD_NAME=android
#        - DETAILS=""

#    - os: linux
#      compiler: gcc
#      language: cpp
#      sudo: false
#      dist: precise
#      cache:
#        apt: true
#        directories:
#          - $HOME/.ccache
#      apt:
#        packages:
#          - ccache
#      env:
#        - BUILD_NAME=big_endian
#        - DETAILS=""

    - os: linux
      arch: s390x
      compiler: gcc
      language: cpp
      sudo: false
      dist: bionic
      cache:
        apt: true
        directories:
          - $HOME/.ccache
      apt:
        packages:
          - ccache
      env:
        - BUILD_NAME=s390x
        - DETAILS=""

    - os: linux
      arch: arm64-graviton2
      virt: lxd
      group: edge
      compiler: gcc
      language: cpp
      sudo: false
      dist: bionic
      cache:
        apt: true
        directories:
          - $HOME/.ccache
      apt:
        packages:
          - ccache
      env:
        - BUILD_NAME=graviton2
        - DETAILS=""

#    - os: linux
#      compiler: gcc
#      language: cpp
#      sudo: required
#      dist: xenial
#      cache:
#        apt: true
#        directories:
#          - $HOME/.ccache
#      env:
#        - BUILD_NAME=sanitize
#        - DETAILS=""

#    - os: linux
#      compiler: gcc
#      language: cpp
#      sudo: required
#      dist: trusty
#      cache:
#        apt: true
#        directories:
#          - $HOME/.ccache
#      env:
#        - BUILD_NAME=ubuntu_1604
#        - DETAILS=""

#    - os: linux
#      compiler: gcc
#      language: cpp
#      sudo: required
#      dist: trusty
#      cache:
#        apt: true
#        directories:
#          - $HOME/.ccache
#      env:
#        - BUILD_NAME=trusty_32bit
#        - DETAILS=""

#    - os: osx
#      language: objective-c
#      compiler: clang
#      cache:
#        apt: true
#        directories:
#          - $HOME/.ccache
#      env:
#        - BUILD_NAME=osx
#        - DETAILS="debug build, libtool"

before_install:
  - ./gdal/ci/travis/${BUILD_NAME}/before_install.sh

install:
  - ./gdal/ci/travis/${BUILD_NAME}/install.sh

script:
  - ./gdal/ci/travis/${BUILD_NAME}/script.sh

notifications:
  irc:
    channels:
       - "irc.freenode.org#gdal-activity"
      #- "irc.freenode.org#gdal"
    use_notice: true
    on_success: change
#
#   email:
#     recipients:
#       - gdal-commits@lists.osgeo.org

