name: MacOS build

on:
    push:
        paths-ignore:
            - 'doc/**'
        branches-ignore:
            - 'backport**'
    pull_request:
        paths-ignore:
            - 'doc/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read  #  to fetch code (actions/checkout)

jobs:

  macos_build:
    # Arm64
    runs-on: macos-14
    if: "!contains(github.event.head_commit.message, '[ci skip]') && !contains(github.event.head_commit.message, '[skip ci]')"
    steps:

      - uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4.1.2

      - uses: conda-incubator/setup-miniconda@030178870c779d9e5e1b4e563269f3aa69b04081 # v3.0.3
        with:
            channels: conda-forge
            auto-update-conda: true

      - name: Install Requirements
        shell: bash -l {0}
        run: |
          source ./ci/travis/osx/before_install.sh

      - name: Build
        shell: bash -l {0}
        run: |
          source ./ci/travis/osx/install.sh

      - name: Run tests
        shell: bash -l {0}
        run: |
          source ./ci/travis/osx/script.sh
        env:
            # Emulate a few Travis-CI env variable so that some tests get properly skipped
            TRAVIS: true
            TRAVIS_OS_NAME: osx
            BUILD_NAME: macos_build_conda
